# Generated by Django 5.1 on 2025-04-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_name',
            new_name='student_class',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id_number',
            field=models.CharField(max_length=20),
        ),
    ]
